import { Link } from 'react-router-dom'
import {
  Sparkles,
  BookOpen,
  Target,
  Clock,
  BrainCircuit,
  ArrowRight,
  CheckCircle2,
  Zap,
  BarChart3,
} from 'lucide-react'
import Card from '../components/Card'

/**
 * LandingPage — Hero section with app intro and CTA
 */
export default function LandingPage() {
  const features = [
    {
      icon: BrainCircuit,
      title: 'AI-Powered Plans',
      description: 'Get personalized study schedules generated by AI based on your goals, level, and available time.',
      color: '#818cf8',
    },
    {
      icon: Target,
      title: 'Goal-Oriented',
      description: 'Set clear learning goals and track your journey with structured daily and weekly milestones.',
      color: '#0ea5e9',
    },
    {
      icon: BarChart3,
      title: 'Track Progress',
      description: 'Visual progress tracking keeps you motivated and helps you stay on course to meet your deadlines.',
      color: '#10b981',
    },
    {
      icon: Zap,
      title: 'Smart Adaptation',
      description: 'Plans adapt to your weak areas and prioritize topics that need the most attention.',
      color: '#f59e0b',
    },
  ]

  const steps = [
    { num: '01', title: 'Set Your Goal', desc: 'Tell us what you want to learn and your timeline.' },
    { num: '02', title: 'Get Your Plan', desc: 'AI generates a customized daily & weekly schedule.' },
    { num: '03', title: 'Start Learning', desc: 'Follow your plan, check off tasks, and track progress.' },
  ]

  return (
    <div>
      {/* ─── Hero Section ─── */}
      <section style={{
        minHeight: 'calc(100vh - 64px)',
        display: 'flex',
        alignItems: 'center',
        position: 'relative',
        overflow: 'hidden',
      }}>
        {/* Background gradient orbs */}
        <div style={{
          position: 'absolute',
          top: '-20%',
          left: '-10%',
          width: '500px',
          height: '500px',
          borderRadius: '50%',
          background: 'radial-gradient(circle, rgba(99,102,241,0.12) 0%, transparent 70%)',
          filter: 'blur(60px)',
          pointerEvents: 'none',
        }} />
        <div style={{
          position: 'absolute',
          bottom: '-20%',
          right: '-10%',
          width: '400px',
          height: '400px',
          borderRadius: '50%',
          background: 'radial-gradient(circle, rgba(14,165,233,0.1) 0%, transparent 70%)',
          filter: 'blur(60px)',
          pointerEvents: 'none',
        }} />

        <div className="container" style={{ position: 'relative', zIndex: 1, paddingTop: '4rem', paddingBottom: '4rem' }}>
          <div style={{
            maxWidth: '720px',
            margin: '0 auto',
            textAlign: 'center',
          }}>
            {/* Badge */}
            <div className="animate-fade-in-up" style={{ marginBottom: '1.5rem' }}>
              <span className="badge badge-primary" style={{ fontSize: '0.8rem', padding: '0.35rem 1rem', gap: '0.35rem', display: 'inline-flex', alignItems: 'center' }}>
                <Sparkles size={14} /> AI-Powered Study Planning
              </span>
            </div>

            {/* Heading */}
            <h1
              className="animate-fade-in-up delay-100"
              style={{
                fontSize: 'clamp(2.2rem, 5vw, 3.5rem)',
                fontWeight: 800,
                lineHeight: 1.15,
                marginBottom: '1.5rem',
                letterSpacing: '-0.03em',
              }}
            >
              Study Smarter with{' '}
              <span className="gradient-text">LearnMate</span>
            </h1>

            {/* Subtitle */}
            <p
              className="animate-fade-in-up delay-200"
              style={{
                fontSize: 'clamp(1rem, 2vw, 1.2rem)',
                color: 'var(--text-secondary)',
                maxWidth: '560px',
                margin: '0 auto 2.5rem',
                lineHeight: 1.6,
              }}
            >
              Tell us your learning goals, and our AI will create a personalized
              study plan with daily tasks, weekly milestones, and real-time
              progress tracking.
            </p>

            {/* CTA Buttons */}
            <div
              className="animate-fade-in-up delay-300"
              style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '1rem', flexWrap: 'wrap' }}
            >
              <Link to="/create-plan" className="btn-primary" style={{ fontSize: '1.05rem', padding: '0.9rem 2rem' }}>
                Start Planning
                <ArrowRight size={18} />
              </Link>
              <Link to="/dashboard" className="btn-secondary" style={{ fontSize: '1.05rem', padding: '0.9rem 2rem' }}>
                <BookOpen size={18} />
                View Dashboard
              </Link>
            </div>
          </div>
        </div>
      </section>

      {/* ─── Features Section ─── */}
      <section style={{ paddingBottom: '5rem' }}>
        <div className="container">
          <div style={{ textAlign: 'center', marginBottom: '3rem' }}>
            <h2 className="animate-fade-in-up" style={{ fontSize: '1.8rem', fontWeight: 700, marginBottom: '0.75rem' }}>
              Everything you need to <span className="gradient-text">ace your goals</span>
            </h2>
            <p style={{ color: 'var(--text-secondary)', maxWidth: '500px', margin: '0 auto' }}>
              LearnMate combines AI intelligence with proven learning strategies.
            </p>
          </div>

          <div style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))',
            gap: '1.25rem',
          }}>
            {features.map((feature, i) => (
              <Card key={i} className={`animate-fade-in-up delay-${(i + 1) * 100}`}>
                <div style={{
                  width: '44px',
                  height: '44px',
                  borderRadius: '12px',
                  background: `${feature.color}18`,
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  marginBottom: '1rem',
                }}>
                  <feature.icon size={22} color={feature.color} />
                </div>
                <h3 style={{ fontSize: '1.05rem', fontWeight: 600, marginBottom: '0.5rem' }}>
                  {feature.title}
                </h3>
                <p style={{ fontSize: '0.875rem', color: 'var(--text-muted)', lineHeight: 1.6 }}>
                  {feature.description}
                </p>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* ─── How It Works ─── */}
      <section style={{ paddingBottom: '6rem' }}>
        <div className="container">
          <div style={{ textAlign: 'center', marginBottom: '3rem' }}>
            <h2 style={{ fontSize: '1.8rem', fontWeight: 700, marginBottom: '0.75rem' }}>
              How it <span className="gradient-text">works</span>
            </h2>
          </div>

          <div style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))',
            gap: '1.5rem',
            maxWidth: '900px',
            margin: '0 auto',
          }}>
            {steps.map((step, i) => (
              <div
                key={i}
                className={`animate-fade-in-up delay-${(i + 1) * 100}`}
                style={{
                  textAlign: 'center',
                  padding: '2rem 1.5rem',
                }}
              >
                <div style={{
                  fontSize: '2.5rem',
                  fontWeight: 800,
                  background: 'linear-gradient(135deg, var(--color-primary), var(--color-secondary))',
                  WebkitBackgroundClip: 'text',
                  WebkitTextFillColor: 'transparent',
                  marginBottom: '1rem',
                }}>
                  {step.num}
                </div>
                <h3 style={{ fontSize: '1.1rem', fontWeight: 600, marginBottom: '0.5rem' }}>
                  {step.title}
                </h3>
                <p style={{ fontSize: '0.875rem', color: 'var(--text-muted)', lineHeight: 1.6 }}>
                  {step.desc}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ─── Footer CTA ─── */}
      <section style={{ paddingBottom: '5rem' }}>
        <div className="container">
          <Card style={{
            textAlign: 'center',
            padding: '3rem 2rem',
            background: 'linear-gradient(135deg, rgba(99,102,241,0.08), rgba(14,165,233,0.08))',
            border: '1px solid rgba(99,102,241,0.2)',
          }}>
            <h2 style={{ fontSize: '1.6rem', fontWeight: 700, marginBottom: '0.75rem' }}>
              Ready to start learning?
            </h2>
            <p style={{ color: 'var(--text-secondary)', marginBottom: '1.5rem', maxWidth: '450px', margin: '0 auto 1.5rem' }}>
              Create your personalized AI study plan in under a minute.
            </p>
            <Link to="/create-plan" className="btn-primary" style={{ fontSize: '1.05rem', padding: '0.9rem 2rem' }}>
              <CheckCircle2 size={18} />
              Create My Plan
            </Link>
          </Card>
        </div>
      </section>
    </div>
  )
}
